import fs from "node:fs";
import path from "node:path";
import { task } from "hardhat/config";
import type { TaskArguments } from "hardhat/types";

type DeploymentFile = {
  address: string;
  abi: unknown;
};

function toTsLiteral(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

task("sync:frontend", "Syncs VoteShield address + ABI into the frontend from deployments/sepolia")
  .addOptionalParam("out", "Frontend output file path", "src/src/config/contracts.ts")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const deploymentPath = path.join(hre.config.paths.root, "deployments", "sepolia", "VoteShield.json");
    if (!fs.existsSync(deploymentPath)) {
      throw new Error(`Missing deployment file: ${deploymentPath}. Deploy to sepolia first.`);
    }

    const raw = fs.readFileSync(deploymentPath, "utf8");
    const parsed = JSON.parse(raw) as DeploymentFile;

    if (!parsed.address || !parsed.abi) {
      throw new Error(`Invalid deployment file: ${deploymentPath}`);
    }

    const outPath = path.join(hre.config.paths.root, String(taskArguments.out));
    const outDir = path.dirname(outPath);
    fs.mkdirSync(outDir, { recursive: true });

    const contents = `// Auto-generated by \`npx hardhat sync:frontend\` after deploying VoteShield to Sepolia.
// Do not hand-edit.

const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000' as const;

export const CONTRACT_ADDRESS = ${JSON.stringify(parsed.address)} as const;
export const CONTRACT_ABI = ${toTsLiteral(parsed.abi)} as const;

export function isContractConfigured(): boolean {
  return CONTRACT_ADDRESS !== ZERO_ADDRESS;
}
`;

    fs.writeFileSync(outPath, contents, "utf8");
    console.log(`Synced VoteShield ABI to ${outPath}`);
  });
