// This file is generated by `npx hardhat sync:frontend` after deploying to Sepolia.
// It is safe to commit, but do not hand-edit it.

export const CONTRACT_ADDRESS = "0x611F9Cd9f88fa0b35901f2967B4aC1A820f1901A";

export const CONTRACT_ABI = [
  {
    type: 'event',
    name: 'PollCreated',
    inputs: [
      { indexed: true, name: 'pollId', type: 'uint256' },
      { indexed: true, name: 'creator', type: 'address' },
      { indexed: false, name: 'endTime', type: 'uint64' },
      { indexed: false, name: 'optionsCount', type: 'uint8' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'VoteCast',
    inputs: [
      { indexed: true, name: 'pollId', type: 'uint256' },
      { indexed: true, name: 'voter', type: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PollFinalized',
    inputs: [
      { indexed: true, name: 'pollId', type: 'uint256' },
      { indexed: true, name: 'finalizer', type: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'function',
    name: 'pollCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'hasVoted',
    stateMutability: 'view',
    inputs: [
      { name: '', type: 'uint256' },
      { name: '', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'createPoll',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'name', type: 'string' },
      { name: 'options', type: 'string[]' },
      { name: 'endTime', type: 'uint64' },
    ],
    outputs: [{ name: 'pollId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'vote',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'pollId', type: 'uint256' },
      { name: 'encryptedChoice', type: 'bytes32' },
      { name: 'inputProof', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'finalize',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'pollId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getPollMeta',
    stateMutability: 'view',
    inputs: [{ name: 'pollId', type: 'uint256' }],
    outputs: [
      { name: 'name', type: 'string' },
      { name: 'endTime', type: 'uint64' },
      { name: 'optionsCount', type: 'uint8' },
      { name: 'creator', type: 'address' },
      { name: 'finalized', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'getPollOptions',
    stateMutability: 'view',
    inputs: [{ name: 'pollId', type: 'uint256' }],
    outputs: [{ name: 'options', type: 'string[]' }],
  },
  {
    type: 'function',
    name: 'getEncryptedCount',
    stateMutability: 'view',
    inputs: [
      { name: 'pollId', type: 'uint256' },
      { name: 'optionIndex', type: 'uint8' },
    ],
    outputs: [{ name: '', type: 'bytes32' }],
  },
] as const;

export function isContractConfigured(): boolean {
  return true
}
